name: magnolia
description: Minecraft-Discord integration software
version: 1.0.0
repository: https://github.com/minecadia-pl/magnolia

environment:
  sdk: ^3.4.4

dependencies:
  json_annotation: ^4.9.0
  oauth2: ^2.0.3
  postgrest: ^2.4.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  shelf_router_generator: ^1.1.0
